### PR TITLE
Fix volpath matching (script/container)

### PR DESCRIPTION
**Pull request by viatcheslavmogilevsky**
https://github.com/chadoe/docker-cleanup-volumes/issues/10

### CODE REVIEW

**Comment by chadoe** [comment]
Thanks, but I really don't want another almost identical script. Should be possible to combine the two scripts though. It's possible to detect if you're running inside a docker container `if [ -f /.dockerinit ]; then`

**Comment by viatcheslavmogilevsky** [comment]
Theoretically such file can be stored outside a container. How about http://stackoverflow.com/a/20012536/1926204 ?

**Comment by chadoe** [comment]
Sure, either one should be fine I think.

**Comment by viatcheslavmogilevsky** [comment]
Pull request closed and then reopened cause git magic )

**Comment by chadoe** [comment]
Nice! Looks good, will try to test it tomorrow.

**Comment by chadoe** [comment]
Thank you.

**Pull request merged**
